### ISSUE TITLE
Is there a way to track how a much a particular user mined ?

### ISSUE THREAD

**Issue by teidova21** [sys-256/Duino-JS#12]
Hi,

Your project seems interesting ! 👍 

I was thinking about giving some kind of compensations for users who lent their CPU.

Is there some way to track how much a particular user mined so I can give him an avatar after .1 cent was mined for example ?

Thanks for reading =D

**Comment by teidova21** [comment]
Ok, sorry for late answer.

I can host the backend server it's not a problem actually.
I'll look into the Duino-Coin API I guess

Does it allow for each worker's work surveillance ?

**Comment by teidova21** [comment]
Sorry for **really** late answer, I've been kinda busy with boring school stuff.
Anyway, I'm still kinda busy atm but I'll let you know if I get something working,
I gotta motivate myself to actually code cause rn I'm mentally exhausted ^^"

Thx for help

**Comment by sys-256** [comment]
Hi, not to stress you, but have you made any progress on it since? Just wondering.

**Comment by sys-256** [comment]
Closing because you're not responding.
