### ISSUE TITLE
I have some questions...

### ISSUE THREAD

**Issue by MDRafi08642** [sys-256/Duino-JS#13]
Your codes work fine...😊

But, will this code ban my duino wallet (webwallet)...?🤔

You can check my website 🙂

Here's my website (hosted on google drive😋) --
https://pjmjmze7uzh9eyeweiwhsa-on.drv.tw/Redirect-Duino/

**Comment by sys-256** [comment]
> Your codes work fine...😊

Nice to hear that :)
> But, will this code ban my duino wallet (webwallet)...?🤔

[It's still listed as "miners known tot work"](https://github.com/revoxhere/duino-coin#other-miners-known-to-work-with-duino-coin), so I don't assume so. Ask revox to assure yourself
> You can check my website 🙂
> 
> Here's my website (hosted on google drive😋) -- https://pjmjmze7uzh9eyeweiwhsa-on.drv.tw/Redirect-Duino/

Nice! Did you know you can host it for free on GitHub Pages as well btw? You'll be able to get the MDRafi08642.github.io url, which is more easy to remember then your current Google Drive solution.
