### ISSUE TITLE
Miner not showing up and not mining

### ISSUE THREAD

**Issue by OlMi1** [sys-256/Duino-JS#14]
I cloned the repo to my webspace and went to the demo website.
My Web Wallet shows an increase of Miners by 1 (as expected), but it does not show in the list. Console output is however received:

```
worker.js:35 CPU0: New job recieved! It contains: 3.0
worker.js:35 CPU1: New job recieved! It contains: 3.0
```

But it does not go further than that. 
Thankful for help!

**Comment by sys-256** [comment]
Fixed by #15, according to my own testing.
