### ISSUE TITLE
Implement a mining_key

### ISSUE THREAD

**Issue by alkhachatryan** [sys-256/Duino-JS#19]
I got an issue when trying to install a miner to my portfolio. The duino coin requires to have a mining key when sending an update about the job.

So in worker.js we have this code repeated 3 times:
`socket.send(`JOB,${username},LOW`);`
After LOW you need to put the mining_key variable. I couldn't see how you use internal variables in this file so I don't open a PR, but an issue instead.

Again, user sets his mining key before calling worker js and passing his mining key and you pass that variable as 4th param, like this:

`socket.send(`JOB,${username},LOW,${miningKey}`);`

**Comment by sys-256** [comment]
Hi @alkhachatryan, thanks for letting me know! I'm a bit busy right now but hopefully I'll be able to add it this weekend.

**Comment by sys-256** [comment]
Hi @alkhachatryan, I've just added mining key functionality in [Duino-JS v4.1](https://github.com/sys-256/Duino-JS/releases/tag/v4.1). Could you please test it and tell me if it works as expected?

**Comment by alkhachatryan** [comment]
Looks like that's ok
