### ISSUE TITLE
Firefox cant connect to wss://server.duinocoin.com:14808/

### ISSUE THREAD

**Issue by viktor02** [sys-256/Duino-JS#9]
On chrome:
![изображение](https://user-images.githubusercontent.com/19672960/128245446-f0916f4a-4e49-4117-8711-780470c20a73.png)

**Comment by sys-256** [comment]
This seems to be a proxy2pool issue again, especially because the web miner has the same issue. And since the web miner says it will be fixed in the upcoming days, the best we can do is wait.

**Comment by sys-256** [comment]
I should be working again.

**Comment by GYKgamer** [comment]
seems to not work again, running this on my web server I get these errors:
![image](https://github.com/sys-256/Duino-JS/assets/41442793/8142f22b-302d-43fc-9a75-3a17331dcabf)
![image](https://github.com/sys-256/Duino-JS/assets/41442793/c2baba9b-513c-4af9-8845-e4795dc2394d)

**Comment by sys-256** [comment]
Hi @GYKgamer, thanks for letting me know about this issue! It seems like the port changed from 14808 to 8443. I've changed this in a7e7df0. You can download the updated minified Duino-JS files here: https://github.com/sys-256/Duino-JS/releases/tag/v3.6.
